# Generated by Django 5.2.14 on 2026-05-19 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelImportQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Исходный файл')),
                ('status', models.CharField(default='pending', max_length=50, verbose_name='Статус')),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='Сырые данные')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Ошибки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработан')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто загрузил')),
            ],
            options={
                'verbose_name': 'Очередь импорта',
                'verbose_name_plural': 'Очередь импорта',
                'db_table': 'excel_import_queue',
            },
        ),
    ]
